import type { NextPage } from "next";

import Head from "next/head";

import AboutSection from "../components/About";
import ContactSection from "../components/Contact";
import HomeSection from "../components/Home";
import ProjectsSection from "../components/Projects";

const Home: NextPage = () => {
  return (
    <div className="container bg-body dark:bg-dbody w-full">
      <Head>
        <title>Personal Portfolio</title>
        <meta content="Generated by create next app" name="description" />
      </Head>
      <main>
        <HomeSection />
        <AboutSection />
        <ProjectsSection />
        <ContactSection />
      </main>
    </div>
  );
};

export default Home;
